# Generated by Django 4.2 on 2023-04-06 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0002_inventory_survivor_delete_teacher_inventory_survivor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
