# Generated by Django 4.2 on 2023-04-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0003_alter_survivor_gender_alter_survivor_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='inventory',
        ),
        migrations.AddField(
            model_name='survivor',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='medication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
