# Generated by Django 4.2 on 2023-04-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0004_remove_survivor_inventory_survivor_ammunition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurvivorInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssn.inventoryitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='ammunition',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='food',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='water',
        ),
        migrations.AlterField(
            model_name='survivor',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='survivorinventory',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zssn.survivor'),
        ),
        migrations.AddField(
            model_name='survivor',
            name='inventory_items',
            field=models.ManyToManyField(related_name='survivors', through='zssn.SurvivorInventory', to='zssn.inventoryitem'),
        ),
    ]
