# Generated by Django 4.2 on 2023-04-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0005_inventoryitem_survivorinventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
