# Generated by Django 4.2 on 2023-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0006_remove_inventoryitem_description_inventoryitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
