# Generated by Django 4.2 on 2023-04-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0008_survivor_password_survivor_user_survivor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='username',
        ),
    ]
