# Generated by Django 4.2 on 2023-04-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0009_remove_survivor_password_remove_survivor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Water', 'Water'), ('Food', 'Food'), ('Medication', 'Medication'), ('Ammunition', 'Ammunition')], max_length=255)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='survivorinventory',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='survivorinventory',
            name='survivor',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='inventory_items',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='status',
        ),
        migrations.AddField(
            model_name='survivor',
            name='infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survivor',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survivor',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='SurvivorInventory',
        ),
        migrations.AddField(
            model_name='item',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zssn.survivor'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('type', 'survivor')},
        ),
    ]
