# Generated by Django 4.2 on 2023-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0010_item_remove_survivorinventory_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
