# Generated by Django 4.2 on 2023-04-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0011_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='value',
        ),
    ]
