# Generated by Django 4.2 on 2023-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0012_remove_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='infection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
